### ISSUE TITLE
Corrupt zip file

### ISSUE THREAD

**Issue by Jaredmmx** [Grandt/PHPZipMerge#5]
I tried to use PHPZipMerge but it returns a corrupt zip file.

				$zipMerge = new ZipMerge\Zip\Stream\ZipMerge('mergedLicenses.zip');
				$zipMerge->appendZip("../FTP/20140331/240673207.zip", "20140331");
				$zipMerge->appendZip("../FTP/20140925/240673207.zip", "20140925");
				$zipMerge->finalize();

Any ideas?

**Comment by Grandt** [comment]
can you send me the two zip files, and the output?

php@grandt.com

**Comment by Grandt** [comment]
Found the problem, will commit a new version in 10 minutes.

**Comment by Jaredmmx** [comment]
Awesome! It works like a charm. 

Thanks!
