### ISSUE TITLE
Corrupt zip file... again

### ISSUE THREAD

**Issue by Jaredmmx** [Grandt/PHPZipMerge#6]
Again I have the same problem as last tuesday.

code is:
            $zipMerge = new ZipMerge\Zip\Stream\ZipMerge('mergedLicenses.zip');
            $zipMerge->appendZip('../FTP/20140925/1436540537.zip', '20140925');
            $zipMerge->appendZip('../FTP/20140925/428984547.zip', '20140925');
            $zipMerge->appendZip('../FTP/20140925/903291386.zip', '20140925');
            $zipMerge->finalize();

I shared with you the files involved in Dropbox

**Comment by Grandt** [comment]
I just ran the code (using test#6.php on DropBox) and had no errors. Both WinRAR and my Linux infozip reports a clean file.
Please upload your mergedLicenses.zip file to the dropbox for comparison.

Is this happening on the same system as before, or a new/different installation? If so, make sure you are pointing to version 1.0.4 in the composer.json file.

**Comment by Jaredmmx** [comment]
Same system.Composer pointing to correct version.

Using just windows file manager to open .zip files. (Windows 7)

Just uploaded merged zip to dropbox

**Comment by Grandt** [comment]
I'm not seeing your mergedLicences.zip. In the mean time, how does your windows explorer react to mergedLicences#6.zip?

And what is your PHP version?

**Comment by Jaredmmx** [comment]
File uploaded is 'mergedLicenses (14).zip' ... dind't upload last time... something failed. Now it's there

mergedLicences#6.zip opens perfectly.

my PHP version is 5.5.12

**Comment by Grandt** [comment]
The end of your zip file contained a massive error log. I pasted that into errorMessage#6.txt on dropbox. It was placed where the central record should have been and had one linebreak character before it. that linebreak could be the problem. 
Everything up till that point appears to be identical between the two files.

**Comment by Jaredmmx** [comment]
Dude! You rock!

Thank you man, and sorry for the inconvenience.... just had to disable web log....

**Comment by Grandt** [comment]
You're welcome :D
